/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

/**
 *
 * @author tushar
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        
        setSize(1155, 738);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Uni LMS Admin Home Page");
        String adminname = GlobalClass.loggedinadmin;
        
        name.setText(adminname+"!");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TitlePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        ChangePasswordPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LogoutPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adcbt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        mcbt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        adtbt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(830, 20, 300, 100);

        TitlePanel.setBackground(new java.awt.Color(51, 51, 51));
        TitlePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TitlePanel.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-username-500 (1).png"))); // NOI18N
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TitlePanel.add(jLabel4);
        jLabel4.setBounds(10, 0, 50, 60);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Welcome");
        TitlePanel.add(jLabel1);
        jLabel1.setBounds(70, 0, 90, 60);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("jLabel2");
        TitlePanel.add(name);
        name.setBounds(160, 0, 220, 60);

        jPanel1.add(TitlePanel);
        TitlePanel.setBounds(0, 0, 370, 60);

        ChangePasswordPanel.setBackground(new java.awt.Color(0, 0, 0));
        ChangePasswordPanel.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-sign-in-form-password-50.png"))); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 50, 50);

        ChangePasswordPanel.add(jPanel4);
        jPanel4.setBounds(10, 0, 50, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Change Password");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ChangePasswordPanel.add(jButton1);
        jButton1.setBounds(60, 0, 130, 50);

        jPanel1.add(ChangePasswordPanel);
        ChangePasswordPanel.setBounds(950, 610, 190, 50);

        LogoutPanel.setBackground(new java.awt.Color(0, 0, 0));
        LogoutPanel.setLayout(null);

        jButton2.setBackground(java.awt.SystemColor.windowText);
        jButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        LogoutPanel.add(jButton2);
        jButton2.setBounds(60, 0, 130, 40);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-logout-26.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel5);
        jLabel5.setBounds(10, 0, 40, 40);

        LogoutPanel.add(jPanel6);
        jPanel6.setBounds(10, 0, 50, 40);

        jPanel1.add(LogoutPanel);
        LogoutPanel.setBounds(950, 660, 190, 40);

        adcbt.setBackground(new java.awt.Color(255, 255, 255));
        adcbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-course-128.png"))); // NOI18N
        adcbt.setBorder(null);
        adcbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adcbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcbtActionPerformed(evt);
            }
        });
        jPanel1.add(adcbt);
        adcbt.setBounds(140, 180, 150, 140);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add Course");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 330, 90, 30);

        mcbt.setBackground(new java.awt.Color(255, 255, 255));
        mcbt.setForeground(new java.awt.Color(255, 255, 255));
        mcbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-course-128 (1).png"))); // NOI18N
        mcbt.setBorder(null);
        mcbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mcbt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mcbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcbtActionPerformed(evt);
            }
        });
        jPanel1.add(mcbt);
        mcbt.setBounds(360, 180, 150, 140);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Manage Teachers");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(820, 330, 150, 30);

        adtbt.setBackground(new java.awt.Color(255, 255, 255));
        adtbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-teacher-128 (1).png"))); // NOI18N
        adtbt.setBorder(null);
        adtbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adtbt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adtbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adtbtActionPerformed(evt);
            }
        });
        jPanel1.add(adtbt);
        adtbt.setBounds(600, 180, 150, 140);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manage Students");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(610, 560, 130, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-admin-settings-male-128.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(820, 180, 150, 150);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Add Teacher");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(630, 330, 94, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-graduate-128.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(360, 420, 150, 140);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Manage Courses");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 330, 120, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/students.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(600, 420, 150, 140);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Add Student");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(380, 560, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1140, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        AdminChange obj = new AdminChange();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        GlobalClass.loggedinadmin="";
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adcbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcbtActionPerformed
        // TODO add your handling code here:
        AdminAddCourse obj = new AdminAddCourse();
        obj.setVisible(true);
    }//GEN-LAST:event_adcbtActionPerformed

    private void mcbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcbtActionPerformed
        // TODO add your handling code here:
        
        AdminViewCourse obj = new AdminViewCourse();
        obj.setVisible(true);
    }//GEN-LAST:event_mcbtActionPerformed

    private void adtbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adtbtActionPerformed
        // TODO add your handling code here:
        AdminAddTeacher obj = new AdminAddTeacher();
        obj.setVisible(true);
    }//GEN-LAST:event_adtbtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AdminViewTeacher obj = new AdminViewTeacher();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AdminAddStudent obj = new AdminAddStudent();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        AdminViewStudent obj = new AdminViewStudent();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangePasswordPanel;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton adcbt;
    private javax.swing.JButton adtbt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton mcbt;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
