/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author tushar
 */
public class AdminAddTeacher extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddTeacher
     */
    File f;
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");
    public AdminAddTeacher() {
        initComponents();
        setSize(1300, 835);
        setTitle("Uni LMS Admin Add Teacher");
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tntf = new javax.swing.JTextField();
        fntf = new javax.swing.JTextField();
        emtf = new javax.swing.JTextField();
        pntf = new javax.swing.JTextField();
        qtf = new javax.swing.JTextField();
        decb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        addta = new javax.swing.JTextArea();
        browsebt = new javax.swing.JButton();
        photolb = new javax.swing.JLabel();
        addbt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Phone No");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 420, 130, 21);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reset");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(630, 720, 100, 21);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Address");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(710, 430, 100, 21);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Email Id");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 330, 130, 21);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Father's Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 240, 130, 21);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Qualification");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 510, 130, 21);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Department");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(710, 140, 130, 21);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Photo");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(710, 230, 90, 21);

        tntf.setBackground(new java.awt.Color(255, 255, 255));
        tntf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tntf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tntf.setBorder(null);
        jPanel1.add(tntf);
        tntf.setBounds(160, 170, 380, 40);

        fntf.setBackground(new java.awt.Color(255, 255, 255));
        fntf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fntf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fntf.setBorder(null);
        jPanel1.add(fntf);
        fntf.setBounds(160, 260, 380, 40);

        emtf.setBackground(new java.awt.Color(255, 255, 255));
        emtf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emtf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emtf.setBorder(null);
        jPanel1.add(emtf);
        emtf.setBounds(160, 350, 380, 40);

        pntf.setBackground(new java.awt.Color(255, 255, 255));
        pntf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pntf.setBorder(null);
        jPanel1.add(pntf);
        pntf.setBounds(160, 440, 380, 40);

        qtf.setBackground(new java.awt.Color(255, 255, 255));
        qtf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        qtf.setBorder(null);
        jPanel1.add(qtf);
        qtf.setBounds(160, 530, 380, 40);

        decb.setBackground(new java.awt.Color(255, 255, 255));
        decb.setForeground(new java.awt.Color(51, 51, 51));
        decb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "C.S.E", "M.E.", "Management", "E.E" }));
        jPanel1.add(decb);
        decb.setBounds(710, 170, 380, 40);

        addta.setBackground(new java.awt.Color(255, 255, 255));
        addta.setColumns(20);
        addta.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        addta.setRows(5);
        jScrollPane1.setViewportView(addta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(710, 460, 390, 120);

        browsebt.setBackground(new java.awt.Color(255, 255, 255));
        browsebt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        browsebt.setForeground(new java.awt.Color(255, 255, 255));
        browsebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-browse-64.png"))); // NOI18N
        browsebt.setBorder(null);
        browsebt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        browsebt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        browsebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebtActionPerformed(evt);
            }
        });
        jPanel1.add(browsebt);
        browsebt.setBounds(900, 340, 70, 70);

        photolb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(photolb);
        photolb.setBounds(710, 260, 180, 150);

        addbt.setBackground(new java.awt.Color(255, 255, 255));
        addbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-add-property-96.png"))); // NOI18N
        addbt.setBorder(null);
        addbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtActionPerformed(evt);
            }
        });
        jPanel1.add(addbt);
        addbt.setBounds(490, 620, 110, 100);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-teacher-100.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(560, 0, 110, 100);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Enter Teacher Details");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(490, 60, 270, 90);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(160, 390, 380, 20);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(160, 210, 380, 20);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(160, 570, 380, 20);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(160, 300, 380, 20);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(160, 480, 380, 20);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Teacher Name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(160, 150, 130, 21);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-reset-80.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 620, 100, 100);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Add Teacher");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(500, 720, 90, 21);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(980, 690, 310, 110);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 50, 50);

        jLabel14.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Back");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 50, 50, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1290, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtActionPerformed
        // TODO add your handling code here:
        
        String tname = tntf.getText();
        String fname = fntf.getText();
        String add = addta.getText();
        String email = emtf.getText();
        String phone = pntf.getText();
        String qual = qtf.getText();
        String depart = decb.getSelectedItem().toString();
        
        int p=(int)(100000+(9999999-100000)*Math.random());
        String pass=Integer.toString(p);
        
        
        
        if(!tname.isEmpty() && !fname.isEmpty() && !add.isEmpty() && !email.isEmpty() && !phone.isEmpty() && !qual.isEmpty() && !depart.isEmpty() && f!=null){
            if(phone.length()==10 && email.contains("@") && !depart.equals("Select Department")){
                
                try
                {
//                    .field("photo",f)
                    
                HttpResponse<String> response = Unirest.post(GlobalClass.serverAddress+"adminaddteacher")
                .queryString("teacher",tname).queryString("fathern",fname).queryString("address",add).queryString("email",email).queryString("phn",phone).queryString("quali",qual).queryString("dept",depart).queryString("pass",pass).field("photo",f).asString(); 
               
               if(response.getStatus()==200)
               {
            
                   String feedback4 = response.getBody();
                   if(feedback4.equals("Fails!!!"))
                   {
//                       JOptionPane.showMessageDialog(this, "Fails!!!");
                       JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Error Occured
                                                                !!! Try Again !!!""", "Uni LMS Admin Add Teacher", JOptionPane.PLAIN_MESSAGE, ic);
                   }
                   else
                   {
//                       String output = "Your Output is";
//                       JOptionPane.showMessageDialog(this, "Your Teacher Id: "+feedback4+"\n Your Password is: "+pass);
                       JOptionPane.showMessageDialog(this, "!!! DONE !!! \n TEACHER ID GENERATED: "+feedback4, "UNI LMS Admin Add Teacher", JOptionPane.PLAIN_MESSAGE, ic);
                       
//                       sms_sender.send(phone, "Teacher Id: "+ feedback4+"\nOTP/Temporary Password: "+pass);
                       
                       sms_sender.send(phone,"Dear " +tname+ "!\nYou are now Enrolled as Teacher.\nTeacher/Username Id: "+feedback4+".\nTemporary Password: "+pass+".\nRegards,\nUNI LMS");
                       
                    
                       tntf.setText(null);
                       fntf.setText(null);
                       addta.setText(null);
                       photolb.setText("Cleared");
                       emtf.setText(null);
                       pntf.setText(null);
                       qtf.setText(null);
                   }
               }
               else
                 {
                    System.out.println(response.getStatusText());
                    }
               
           
             }
            
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
            }
            
            else
            {
//                JOptionPane.showMessageDialog(this, "Invalid Phone Number or Email or Select Department");
                JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Invalid Mobile No.
                                                                OR
                                                                Invalid Email Id
                                                                !!! Try Again !!!""", "Uni LMS Admin Add Teacher", JOptionPane.PLAIN_MESSAGE, ic);
            }
        }
        else{
//            JOptionPane.showMessageDialog(this, "Empty field Exists");
             JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Empty Field Exists
                                                                !!! All Fields are Required !!!""", "Uni LMS Admin Add Teacher", JOptionPane.PLAIN_MESSAGE, ic);
        }
        
        
    }//GEN-LAST:event_addbtActionPerformed

    private void browsebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebtActionPerformed
        // TODO add your handling code here:
        
        JFileChooser choose = new JFileChooser();
        int ans = choose.showOpenDialog(this);
        if(ans == JFileChooser.APPROVE_OPTION)
        {
            f = choose.getSelectedFile();
        }
        ImageIcon icon = new ImageIcon(f.getPath());
        Image img = icon.getImage().getScaledInstance(photolb.getWidth(),photolb.getHeight(), Image.SCALE_SMOOTH);
        photolb.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_browsebtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tntf.setText(null);
        fntf.setText(null);
        addta.setText(null);
        photolb.setText("Cleared");
        emtf.setText(null);
        pntf.setText(null);
        qtf.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbt;
    private javax.swing.JTextArea addta;
    private javax.swing.JButton browsebt;
    private javax.swing.JComboBox<String> decb;
    private javax.swing.JTextField emtf;
    private javax.swing.JTextField fntf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel photolb;
    private javax.swing.JTextField pntf;
    private javax.swing.JTextField qtf;
    private javax.swing.JTextField tntf;
    // End of variables declaration//GEN-END:variables
}
