/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author tushar
 */
public class AdminAddCourse extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddCourse
     */
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");
    public AdminAddCourse() {
        initComponents();
        setSize(1240, 675);
        setTitle("Uni LMS Admin Add Course");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deptlb = new javax.swing.JLabel();
        deptcb = new javax.swing.JComboBox<>();
        cnlb = new javax.swing.JLabel();
        cntf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        smcb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        acbt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        backbt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cabt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        deptlb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deptlb.setForeground(new java.awt.Color(51, 51, 51));
        deptlb.setText("Department");
        jPanel1.add(deptlb);
        deptlb.setBounds(110, 240, 140, 40);

        deptcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "C.S.E", "M.E", "E.E", "Management" }));
        deptcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptcbActionPerformed(evt);
            }
        });
        jPanel1.add(deptcb);
        deptcb.setBounds(110, 280, 420, 40);

        cnlb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cnlb.setForeground(new java.awt.Color(51, 51, 51));
        cnlb.setText("Course Name");
        jPanel1.add(cnlb);
        cnlb.setBounds(110, 130, 110, 40);

        cntf.setBackground(new java.awt.Color(255, 255, 255));
        cntf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cntf.setForeground(new java.awt.Color(51, 51, 51));
        cntf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cntf.setBorder(null);
        cntf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cntfFocusLost(evt);
            }
        });
        jPanel1.add(cntf);
        cntf.setBounds(110, 160, 420, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Semester");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 350, 120, 40);

        smcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        smcb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                smcbFocusLost(evt);
            }
        });
        jPanel1.add(smcb);
        smcb.setBounds(110, 390, 420, 40);

        descta.setColumns(20);
        descta.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        descta.setRows(5);
        jScrollPane1.setViewportView(descta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(650, 180, 510, 260);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Course Description");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(650, 140, 170, 40);

        acbt.setBackground(java.awt.SystemColor.windowText);
        acbt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acbt.setForeground(new java.awt.Color(255, 255, 255));
        acbt.setText("Add Course");
        acbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acbtActionPerformed(evt);
            }
        });
        jPanel1.add(acbt);
        acbt.setBounds(390, 490, 160, 60);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(920, 540, 300, 100);

        backbt.setBackground(new java.awt.Color(255, 255, 255));
        backbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        backbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        jPanel1.add(backbt);
        backbt.setBounds(0, 0, 50, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Back");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-3, 40, 50, 16);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-course-50.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 20, 60, 60);

        jLabel6.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter Course Details");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(500, 70, 220, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(110, 200, 420, 3);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("*Eg: BTECH, btech ('.' Not Allowed:- B.Tech, b.tech)");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 200, 270, 20);

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("*Only 200 Characters Allowed");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(990, 440, 170, 16);

        cabt.setBackground(java.awt.SystemColor.windowText);
        cabt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cabt.setForeground(new java.awt.Color(255, 255, 255));
        cabt.setText("Clear All");
        cabt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cabt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabtActionPerformed(evt);
            }
        });
        jPanel1.add(cabt);
        cabt.setBounds(610, 490, 150, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1240, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cntfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cntfFocusLost
        // TODO add your handling code here:

        String coursen = cntf.getText().toUpperCase();

        if (coursen.equals("BTECH")) {
            smcb.removeAllItems();

            for (int i = 1; i <= 8; i++) {
                smcb.addItem(i + "");
            }

        } else if (coursen.startsWith("MTECH")) {
            smcb.removeAllItems();

            for (int i = 1; i <= 4; i++) {
                smcb.addItem(i + "");
            }
        } else if (coursen.startsWith("B") || coursen.startsWith("MCA")) {
            smcb.removeAllItems();

            for (int i = 1; i <= 6; i++) {
                smcb.addItem(i + "");
            }
        }
    }//GEN-LAST:event_cntfFocusLost

    private void smcbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_smcbFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_smcbFocusLost

    private void deptcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptcbActionPerformed

    private void acbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acbtActionPerformed
        // TODO add your handling code here:

        new Thread(new Runnable() {
            @Override
            public void run() {

                String cname = cntf.getText();
                String dname = deptcb.getSelectedItem().toString();
                System.out.println(dname);

                String snum = smcb.getSelectedItem().toString();
                String desc = descta.getText();

                if (!cname.isEmpty() && !dname.isEmpty() && !snum.isEmpty() && !desc.isEmpty()) {
                    if (!dname.equals("Select Department")) {
                        try {
                            HttpResponse<String> response = Unirest.get("http://localhost:8080/adminaddcourse")
                                    .queryString("coursename", cname).queryString("department", dname).queryString("semester", snum).queryString("description", desc).asString();

                            if (response.getStatus() == 200) {
                                String feedback2 = response.getBody();
                                if (feedback2.equals("Course Added !!!")) {
//                                    JOptionPane.showMessageDialog(rootPane, "Course Added !!!");
                                    JOptionPane.showMessageDialog(rootPane, """
                                                                !!! Done !!!
                                                                Course Added""", "Uni LMS Admin Add Course", JOptionPane.PLAIN_MESSAGE, ic);
                                } else {
//                                    JOptionPane.showMessageDialog(rootPane, "Course Already Exists");
                                    JOptionPane.showMessageDialog(rootPane, """
                                                                !!! OOPS !!!
                                                                Course Already Exists""", "Uni LMS Admin Add Course", JOptionPane.PLAIN_MESSAGE, ic);
                                }

                            } else {
                                System.out.println(response.getStatusText());
                            }

                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    } else {
//                        JOptionPane.showMessageDialog(rootPane, "Select Department");
                                                            JOptionPane.showMessageDialog(rootPane, """
                                                                !!! OOPS !!!
                                                                Select Department""", "Uni LMS Admin Add Course", JOptionPane.PLAIN_MESSAGE, ic);
                    }

                } else {
//                    JOptionPane.showMessageDialog(rootPane, "Empty Field Exists");
                    JOptionPane.showMessageDialog(rootPane, """
                                                                !!! OOPS !!!
                                                                Empty Field Exists""", "Uni LMS Admin Add Course", JOptionPane.PLAIN_MESSAGE, ic);
                }

            }
        }).start();


    }//GEN-LAST:event_acbtActionPerformed

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backbtActionPerformed

    private void cabtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabtActionPerformed
        // TODO add your handling code here:

        cntf.setText(null);
        descta.setText(null);
    }//GEN-LAST:event_cabtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acbt;
    private javax.swing.JButton backbt;
    private javax.swing.JButton cabt;
    private javax.swing.JLabel cnlb;
    private javax.swing.JTextField cntf;
    private javax.swing.JComboBox<String> deptcb;
    private javax.swing.JLabel deptlb;
    private javax.swing.JTextArea descta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> smcb;
    // End of variables declaration//GEN-END:variables
}
