/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Image;
import java.io.File;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author tushar
 */
public class AdminAddStudent extends javax.swing.JFrame {

    File f;

    /**
     * Creates new form AddAdminStudent
     */
    
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");
    public AdminAddStudent() {

        initComponents();
        setTitle("Uni LMS Admin Add Student");
        
        
        setSize(1235, 850);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        departcb = new javax.swing.JComboBox<>();
        ccb = new javax.swing.JComboBox<>();
        semcb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        sntf = new javax.swing.JTextField();
        fntf = new javax.swing.JTextField();
        mntf = new javax.swing.JTextField();
        addtf = new javax.swing.JTextField();
        mbtf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        departcb.setBackground(new java.awt.Color(255, 255, 255));
        departcb.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        departcb.setForeground(new java.awt.Color(51, 51, 51));
        departcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "C.S.E", "Management", "E.E.", "M.E." }));
        departcb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departcbItemStateChanged(evt);
            }
        });
        jPanel1.add(departcb);
        departcb.setBounds(720, 390, 380, 40);

        ccb.setBackground(new java.awt.Color(255, 255, 255));
        ccb.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ccb.setForeground(new java.awt.Color(51, 51, 51));
        ccb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ccbItemStateChanged(evt);
            }
        });
        ccb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ccbFocusLost(evt);
            }
        });
        jPanel1.add(ccb);
        ccb.setBounds(720, 490, 380, 40);

        semcb.setBackground(new java.awt.Color(255, 255, 255));
        semcb.setForeground(new java.awt.Color(51, 51, 51));
        semcb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                semcbItemStateChanged(evt);
            }
        });
        jPanel1.add(semcb);
        semcb.setBounds(720, 580, 380, 40);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Select from Available Semesters");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(720, 550, 240, 20);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Father Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 220, 110, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Mother Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 310, 110, 20);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 400, 110, 20);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Mobile");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 490, 60, 20);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Email Id");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 570, 110, 20);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Upload Photo");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(720, 170, 110, 20);

        emailtf.setBackground(new java.awt.Color(255, 255, 255));
        emailtf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emailtf.setBorder(null);
        jPanel1.add(emailtf);
        emailtf.setBounds(90, 590, 410, 40);

        sntf.setBackground(new java.awt.Color(255, 255, 255));
        sntf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sntf.setBorder(null);
        jPanel1.add(sntf);
        sntf.setBounds(90, 150, 410, 40);

        fntf.setBackground(new java.awt.Color(255, 255, 255));
        fntf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fntf.setBorder(null);
        jPanel1.add(fntf);
        fntf.setBounds(90, 240, 410, 40);

        mntf.setBackground(new java.awt.Color(255, 255, 255));
        mntf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mntf.setBorder(null);
        jPanel1.add(mntf);
        mntf.setBounds(90, 330, 410, 40);

        addtf.setBackground(new java.awt.Color(255, 255, 255));
        addtf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addtf.setBorder(null);
        jPanel1.add(addtf);
        addtf.setBounds(90, 420, 410, 40);

        mbtf.setBackground(new java.awt.Color(255, 255, 255));
        mbtf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mbtf.setBorder(null);
        jPanel1.add(mbtf);
        mbtf.setBounds(90, 510, 410, 40);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Student Name");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(90, 130, 110, 20);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Select Department");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(720, 360, 140, 30);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Select from Available Courses");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(720, 460, 220, 20);

        photolb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(photolb);
        photolb.setBounds(720, 200, 160, 150);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-browse-64.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(890, 280, 90, 70);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-add-property-96.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 650, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-mortarboard-96.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 10, 100, 80);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(90, 630, 410, 3);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(90, 190, 410, 3);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(90, 280, 410, 3);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(90, 370, 410, 3);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(90, 460, 410, 3);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(90, 550, 410, 3);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(560, 50, 100, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Enter Student");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 10, 200, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reset");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(650, 750, 100, 21);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(920, 0, 300, 120);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-reset-80.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(650, 650, 90, 100);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Add Student");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(520, 750, 100, 21);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(0, 0, 54, 50);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Back");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(0, 50, 50, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1220, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departcbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departcbItemStateChanged
        // TODO add your handling code here:

        new Thread(new Runnable() {
            @Override
            public void run() {

                String depart = departcb.getSelectedItem().toString();
                try {
                    ccb.removeAllItems();

                    HttpResponse<String> response = Unirest.get("http://localhost:8080/getcourse").queryString("depart", depart).asString();

                    //  System.out.println(ans4);
                    if (response.getStatus() == 200) {
                        ccb.removeAllItems();
                        String ans4 = response.getBody();

                        StringTokenizer st4 = new StringTokenizer(ans4, "#$#");
                        while (st4.hasMoreTokens()) {

                            ccb.addItem(st4.nextToken());
                        }

                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        }).start();


    }//GEN-LAST:event_departcbItemStateChanged

    private void ccbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ccbFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_ccbFocusLost

    private void semcbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_semcbItemStateChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_semcbItemStateChanged

    private void ccbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ccbItemStateChanged
        // TODO add your handling code here:
        new Thread(new Runnable() {
            @Override
            public void run() {
                String course = ccb.getSelectedItem().toString();
                String de = departcb.getSelectedItem().toString();
                try {
                    HttpResponse<String> response = Unirest.get("http://localhost:8080/getsemester").queryString("course", course).queryString("de", de).asString();
                    if (response.getStatus() == 200) {
                        semcb.removeAllItems();
                        String ans5 = response.getBody();

                        StringTokenizer st5 = new StringTokenizer(ans5, "#$#$");
                        while (st5.hasMoreTokens()) {

                            semcb.addItem(st5.nextToken());
                        }

                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        }).start();
    }//GEN-LAST:event_ccbItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String studentname = sntf.getText();
        String fathername = fntf.getText();
        String mothername = mntf.getText();
        String add = addtf.getText();
        String mobile = mbtf.getText();
        String email = emailtf.getText();
        String departn = departcb.getSelectedItem().toString();
        String coursename = ccb.getSelectedItem().toString();
        String semname = semcb.getSelectedItem().toString();

        int p2 = (int) (100000 + (9999999 - 100000) * Math.random());
        String pass2 = Integer.toString(p2);

        if (!studentname.isEmpty() && !fathername.isEmpty() && !mothername.isEmpty() && !add.isEmpty() && !mobile.isEmpty() && !email.isEmpty() && !departn.isEmpty() && !coursename.isEmpty() && !semname.isEmpty()) 
        {
            if(mobile.length()==10 & email.contains("@"))
            {
            try {
                HttpResponse<String> response = Unirest.post("http://localhost:8080/adminaddstudent")
                        .queryString("student_name", studentname)
                        .queryString("father_name", fathername)
                        .queryString("mother_name", mothername)
                        .queryString("add", add)
                        .queryString("mobile", mobile)
                        .queryString("email", email)
                        .queryString("depart", departn)
                        .queryString("coursename", coursename)
                        .queryString("semname", semname)
                        .queryString("pass", pass2)
                        .field("photo", f)
                        .asString();

                if (response.getStatus() == 200) {

                    String feedback5 = response.getBody();
                    if (feedback5.equals("Fails!!!")) {
//                        JOptionPane.showMessageDialog(this, "Fails!!!");
                        JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Error Occured
                                                                !!! Try Again !!!""", "Uni LMS Admin Add Student", JOptionPane.PLAIN_MESSAGE, ic);
                    } else {
//                       String output = "Your Output is";
//                        JOptionPane.showMessageDialog(this, "Your Student Id: " + feedback5 + "\n Your Password is: " + pass2);
                        JOptionPane.showMessageDialog(this, """
                                                                !!! Done !!!
                                                                Student Id Generated: """ + feedback5+
                                                                """ 
                                                                \nOTP/Temporary Password Generated: 
                                                                """+pass2
                                                                 , "Uni LMS Admin Add Student", JOptionPane.PLAIN_MESSAGE, ic);
                        
                        sntf.setText(null);
                        fntf.setText(null);
                        mntf.setText(null);
                        addtf.setText("Cleared");
                        mbtf.setText(null);
                        emailtf.setText(null);

                    }
                }
                else {
                    System.out.println(response.getStatusText());
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
            else
            {
//                JOptionPane.showMessageDialog(this, "Invalid Mobile No. OR Ivalid Email!");
                JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Invalid Mobile No.
                                                                OR
                                                                Invalid Email Id
                                                                !!! Try Again !!!""", "Uni LMS Admin Add Student", JOptionPane.PLAIN_MESSAGE, ic);
            }
        }
        else
        {
//                JOptionPane.showMessageDialog(this, "Empty Field Exists!!");
                JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Empty Field Exists
                                                                !!! All Fields are Required !!!""", "Uni LMS Admin Add Student", JOptionPane.PLAIN_MESSAGE, ic);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JFileChooser choose = new JFileChooser();
        int ans = choose.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = choose.getSelectedFile();
        }
        ImageIcon icon = new ImageIcon(f.getPath());
        Image img = icon.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
        photolb.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        sntf.setText(null);
        fntf.setText(null);
        emailtf.setText(null);
        mbtf.setText(null);
        mntf.setText(null);
        addtf.setText(null);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addtf;
    private javax.swing.JComboBox<String> ccb;
    public javax.swing.JComboBox<String> departcb;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField fntf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField mbtf;
    private javax.swing.JTextField mntf;
    private javax.swing.JLabel photolb;
    private javax.swing.JComboBox<String> semcb;
    private javax.swing.JTextField sntf;
    // End of variables declaration//GEN-END:variables
}
