/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author tushar
 */
public class AdminViewTeacher extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewTeacher
     */
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");

    ArrayList<TeacherDetails> al2;
    mytablemodel2 tm2;

    public AdminViewTeacher() {
        initComponents();

        al2 = new ArrayList<>();
        tm2 = new mytablemodel2();
//        fetchallteacher();
        teachertb.setModel(tm2);

//        setResizable(false);
        setTitle("Uni LMS Admin Manage Teachers");
        setSize(1196, 900);
        setLocationRelativeTo(null);
        setResizable(false);
        teachertb.getColumnModel().getColumn(7).setCellRenderer(new ImageRenderer());
        teachertb.setRowHeight(60);

    }

    private void fetchallteacher() {
        String dept = deptcb.getSelectedItem().toString();
        try {
            HttpResponse<String> response = Unirest.get("http://localhost:8080/adminviewteacher").queryString("dept", dept).asString();

            String ans2 = response.getBody();

            System.out.println(ans2);
            StringTokenizer st = new StringTokenizer(ans2, "$$");

            al2.clear();
            while (st.hasMoreTokens()) {
                String cdet = st.nextToken();
                StringTokenizer st2 = new StringTokenizer(cdet, ";;;");

                String ti = st2.nextToken();
                String tn = st2.nextToken();
                String fn = st2.nextToken();
                String ad = st2.nextToken();
                String em = st2.nextToken();
                String pn = st2.nextToken();
                String qual = st2.nextToken();
                String de = st2.nextToken();
                String ph = st2.nextToken();

//               CourseDetails ob= new CourseDetails(cn, dept, des, sem);
//               al.add(ob);
                al2.add(new TeacherDetails(ti, tn, fn, ad, em, pn, qual, de, ph));

            }

            tm2.fireTableDataChanged();
            //table model

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    class mytablemodel2 extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return al2.size();
        }

        @Override
        public int getColumnCount() {
            return 8;
        }

        @Override
        public String getColumnName(int j) {
            String c[] = {"Teacher Name", "Father's Name", "Address", "Email_id", "Phone_Num", "Qualification", "Department", "Photo"};
            return c[j];
        }

        @Override
        public Object getValueAt(int i, int j) {

            if (j == 0) {
                return al2.get(i).tn;
            } else if (j == 1) {
                return al2.get(i).fn;
            } else if (j == 2) {
                return al2.get(i).ad;
            } else if (j == 3) {
                return al2.get(i).em;
            } else if (j == 4) {
                return al2.get(i).pn;
            } else if (j == 5) {
                return al2.get(i).qual;
            } else if (j == 6) {
                return al2.get(i).de;
            } else {
                return al2.get(i).ph;
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teachertb = new javax.swing.JTable();
        deptcb = new javax.swing.JComboBox<>();
        fetchbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        teachertb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(teachertb);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 240, 1000, 400);

        deptcb.setBackground(new java.awt.Color(255, 255, 255));
        deptcb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deptcb.setForeground(new java.awt.Color(51, 51, 51));
        deptcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "C.S.E", "Management", "M.E.", "E.E." }));
        deptcb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(deptcb);
        deptcb.setBounds(390, 140, 360, 50);

        fetchbt.setBackground(new java.awt.Color(255, 255, 255));
        fetchbt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fetchbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-view-48.png"))); // NOI18N
        fetchbt.setBorder(null);
        fetchbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetchbt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fetchbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchbtActionPerformed(evt);
            }
        });
        jPanel1.add(fetchbt);
        fetchbt.setBounds(760, 140, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-teacher-96.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(520, 0, 96, 90);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Teachers");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 80, 150, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Department");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 140, 80, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Show");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(770, 190, 37, 16);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 50, 50);

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Back");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 50, 50, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(880, 750, 300, 100);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-delete-64.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 670, 60, 60);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Delete");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(580, 730, 40, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1180, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fetchbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchbtActionPerformed
        // TODO add your handling code here:
        fetchallteacher();
    }//GEN-LAST:event_fetchbtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int row = teachertb.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "No Row Selected");
        } else {
            int sel = JOptionPane.showConfirmDialog(this, "Are You Sure You Want to Delete", "Uni LMS Delete Confirm Dialog Box", JOptionPane.YES_NO_OPTION);
            if (sel == JOptionPane.YES_OPTION) {
                String ti = al2.get(row).ti;

                try {
                    HttpResponse<String> response = Unirest.get("http://localhost:8080/admindeleteteacher")
                            .queryString("teach_id", ti).asString();

                    if (response.getStatus() == 200) {
                        String feedback4 = response.getBody();
                        if (feedback4.equals("Teacher Deleted !!!")) {

                            fetchallteacher();
//                        JOptionPane.showMessageDialog(this, "Teacher Deleted");
                            JOptionPane.showMessageDialog(this, """
                                                                !!! Done !!!
                                                                Teacher Record Deleted""", "Uni LMS Manage Student", JOptionPane.PLAIN_MESSAGE, ic);

                        } else {
                            System.out.println(response.getStatusText());
                        }
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Operation Cancelled""", "Uni LMS Manage Teacher", JOptionPane.PLAIN_MESSAGE, ic);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    class ImageRenderer extends DefaultTableCellRenderer {

        JLabel lbl = new JLabel();

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            try {
                URL url = new URL("http://localhost:8080/getresource/" + al2.get(row).ph);
                BufferedImage img = ImageIO.read(url);
                Image newimg = img.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                lbl.setIcon(new ImageIcon(newimg));

            } catch (Exception ex) {
                ex.printStackTrace();
            }

            return lbl;

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> deptcb;
    private javax.swing.JButton fetchbt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable teachertb;
    // End of variables declaration//GEN-END:variables
}
