/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author tushar
 */
public class AdminChange extends javax.swing.JFrame {

    /**
     * Creates new form AdminChange
     */
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");
    public AdminChange() {
        initComponents();
        setSize(1030, 655);
        String adn = GlobalClass.loggedinadmin;
        adminusername.setText(adn);
        adminusername.setEditable(false);
        setTitle("Uni LMS Admin Change Password");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminusername = new javax.swing.JTextField();
        optf = new javax.swing.JPasswordField();
        nptf = new javax.swing.JPasswordField();
        cptf = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        changebt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        adminusername.setBackground(new java.awt.Color(255, 255, 255));
        adminusername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminusername.setForeground(new java.awt.Color(51, 51, 51));
        adminusername.setText("Usename");
        adminusername.setBorder(null);
        adminusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminusernameActionPerformed(evt);
            }
        });
        jPanel1.add(adminusername);
        adminusername.setBounds(620, 150, 270, 30);

        optf.setBackground(new java.awt.Color(255, 255, 255));
        optf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        optf.setForeground(new java.awt.Color(51, 51, 51));
        optf.setBorder(null);
        jPanel1.add(optf);
        optf.setBounds(620, 240, 270, 30);

        nptf.setBackground(new java.awt.Color(255, 255, 255));
        nptf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nptf.setForeground(new java.awt.Color(51, 51, 51));
        nptf.setBorder(null);
        jPanel1.add(nptf);
        nptf.setBounds(620, 320, 270, 30);

        cptf.setBackground(new java.awt.Color(255, 255, 255));
        cptf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cptf.setForeground(new java.awt.Color(51, 51, 51));
        cptf.setBorder(null);
        jPanel1.add(cptf);
        cptf.setBounds(620, 410, 270, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Old Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(620, 210, 120, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("New Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 300, 140, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Confirm Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(620, 380, 160, 30);

        changebt.setBackground(new java.awt.Color(51, 51, 51));
        changebt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changebt.setForeground(new java.awt.Color(255, 255, 255));
        changebt.setText("Change Password");
        changebt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtActionPerformed(evt);
            }
        });
        jPanel1.add(changebt);
        changebt.setBounds(670, 520, 170, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Login UNI Reszed.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 70, 400, 420);

        jLabel5.setFont(new java.awt.Font("Javanese Text", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Change Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 70, 200, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(580, 103, 220, 10);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/user (1).png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 150, 30, 30);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(620, 180, 270, 10);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(620, 270, 270, 3);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(620, 350, 270, 10);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(620, 440, 270, 10);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("All Inputs are Case Sensitive*");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(710, 450, 180, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/PassIcon.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(580, 210, 30, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 50, 40);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Back");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 40, 50, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminusernameActionPerformed

    private void changebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtActionPerformed
        
        int sel = JOptionPane.showConfirmDialog(this, "Are You Sure You Want to Change Password", "Uni LMS Delete Confirm Dialog Box", JOptionPane.YES_NO_OPTION);
        if(sel==JOptionPane.YES_OPTION)
        {
        
        String np = nptf.getText();
        String cp = cptf.getText();
        String op = optf.getText();
        
        
        if(!np.isEmpty() && !cp.isEmpty() && !op.isEmpty())
        {
            if(np.equals(cp))
            {
                
            try
            {
                String u = adminusername.getText();
                String p = optf.getText();
                String p2 = nptf.getText();
                
                HttpResponse<String> response = Unirest.get("http://localhost:8080/adminchangepassword")
                .queryString("user",u).queryString("pass",p).queryString("newpass",p2).asString();
                
                if(response.getStatus()==200)
                {
                    String feedback =  response.getBody();
                    if(feedback.equals("Password Changed !!!"))
                    {
                        JOptionPane.showMessageDialog(this, """
                                                                !!! Done !!!
                                                                Password Changed""", "Uni LMS Admin Password Change", JOptionPane.PLAIN_MESSAGE, ic);
                        optf.setText(null);
                        nptf.setText(null);
                        cptf.setText(null);
                        dispose();

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, """
                                                                !!! Error !!!
                                                                Incorrect Credentials""", "Uni LMS Admin Password Change", JOptionPane.PLAIN_MESSAGE, ic);
                        optf.setText(null);
                        nptf.setText(null);
                        cptf.setText(null);
                    }
                    
                    
                }
            }
            
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
            }
            else
            {
                
                JOptionPane.showMessageDialog(this, """
                                                                !!! Error !!!
                                                                Confirm Password and
                                                                New Password Are Not Same""", "Uni LMS Admin Password Change", JOptionPane.PLAIN_MESSAGE, ic);
                optf.setText(null);
                nptf.setText(null);
                cptf.setText(null);
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog(this, """
                                                !!! Error !!! 
                                                Empty Field Exists
                                                !!! All Fields are Required !!!
                                                ""","Uni LMS Teacher Admin Change", JOptionPane.PLAIN_MESSAGE, ic);
        }
        }
        
        else
        {
            JOptionPane.showMessageDialog(this, """
                                                !!! OOPS !!! 
                                                Operation Cancelled
                                                ""","Uni LMS Teacher Admin Change", JOptionPane.PLAIN_MESSAGE, ic);
        }
        
    }//GEN-LAST:event_changebtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminusername;
    private javax.swing.JButton changebt;
    private javax.swing.JPasswordField cptf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPasswordField nptf;
    private javax.swing.JPasswordField optf;
    // End of variables declaration//GEN-END:variables
}
