/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author tushar
 */
public class AdminViewCourse extends javax.swing.JFrame {

    ArrayList<CourseDetails> al;
    mytablemodel tm;
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");

    /**
     * Creates new form AdminViewCourse
     */
    public AdminViewCourse() {
        initComponents();

//        coursetb.getColumnModel().getColumn(0).s;
        al = new ArrayList<>();
        tm = new mytablemodel();
        setTitle("Uni LMS Admin Manage Course");

        fetchallcourse();

        coursetb.setModel(tm);

        setResizable(false);
        setSize(1160, 820);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private void fetchallcourse() {
        System.out.println("func called");
        try {
            HttpResponse<String> response = Unirest.get("http://localhost:8080/adminviewcourse").asString();

            String ans = response.getBody();
            StringTokenizer st = new StringTokenizer(ans, "$$");

            al.clear();
            while (st.hasMoreTokens()) {
                String cdet = st.nextToken();
                StringTokenizer st2 = new StringTokenizer(cdet, ";;;");

                String cn = st2.nextToken();
                String dept = st2.nextToken();
                String des = st2.nextToken();
                String sem = st2.nextToken();
//               CourseDetails ob= new CourseDetails(cn, dept, des, sem);
//               al.add(ob);
                al.add(new CourseDetails(cn, dept, des, sem));

            }

            tm.fireTableDataChanged();
            //table model

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    class mytablemodel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public String getColumnName(int j) {
            String c[] = {"Course Name", "Department", "Semester", "Description"};
            return c[j];
        }

        @Override
        public Object getValueAt(int i, int j) {

            if (j == 0) {
                return al.get(i).cn;
            } else if (j == 1) {
                return al.get(i).dept;
            } else if (j == 2) {
                return al.get(i).sem;
            } else {
                return al.get(i).des;
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursetb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backbt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        deletebt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        coursetb.setBackground(new java.awt.Color(51, 51, 51));
        coursetb.setForeground(new java.awt.Color(255, 255, 255));
        coursetb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        coursetb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coursetb.setGridColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(coursetb);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 160, 950, 480);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(840, 0, 300, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-course-58.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 70, 60, 70);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Course Details");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 70, 220, 70);

        backbt.setBackground(new java.awt.Color(255, 255, 255));
        backbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        jPanel1.add(backbt);
        backbt.setBounds(0, 0, 50, 40);

        jLabel4.setDisplayedMnemonic('2');
        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Back");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 40, 50, 30);

        deletebt.setBackground(new java.awt.Color(255, 255, 255));
        deletebt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deletebt.setForeground(new java.awt.Color(51, 51, 51));
        deletebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-delete-64.png"))); // NOI18N
        deletebt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        deletebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtActionPerformed(evt);
            }
        });
        jPanel1.add(deletebt);
        deletebt.setBounds(540, 670, 60, 60);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Delete");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(540, 730, 60, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1150, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backbtActionPerformed

    private void deletebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtActionPerformed
        // TODO add your handling code here:

        int row = coursetb.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "No Row Selected");

        } else 
        {
            int sel = JOptionPane.showConfirmDialog(this, "Are You Sure You Want to Delete", "Uni LMS Delete Confirm Dialog Box", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, ic);
            if(sel==JOptionPane.YES_OPTION)
            {
            
            String course = al.get(row).cn;
            String se = al.get(row).sem;
            String de = al.get(row).dept;

//            System.out.println(row);
//            System.out.println(course);
//            System.out.println(se);
//            System.out.println(de);
            try {
                HttpResponse<String> response = Unirest.get("http://localhost:8080/admindeletecourse")
                        .queryString("course", course).queryString("depart", de).queryString("sem", se).asString();

                if (response.getStatus() == 200) {
                    String feedback3 = response.getBody();
                    if (feedback3.equals("Course Deleted !!!")) {
                        JOptionPane.showMessageDialog(this, "Course Deleted");
                        fetchallcourse();

                    } else {
                        System.out.println(response.getStatusText());
                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
            else
            {
                JOptionPane.showMessageDialog(this, "Delete Cancelled");
            }
        }
    }//GEN-LAST:event_deletebtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbt;
    private javax.swing.JTable coursetb;
    private javax.swing.JButton deletebt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
