/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author tushar
 */
public class AdminViewStudent extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewStudent
     */
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");
    ArrayList<Student> al2;
    mytablemodel2 tm2;
    public AdminViewStudent() {
        initComponents();
        
        
//        Dimension d= Toolkit.getDefaultToolkit().getScreenSize();
//        setSize(d.getSize());
        al2 = new ArrayList<>();
        tm2 = new mytablemodel2();
//        fetchallteacher();
        studenttb.setModel(tm2);
        
        setTitle("Uni LMS Admin Manage Students");
        setSize(1245, 810);
        setResizable(false);
        setLocationRelativeTo(null);
        
        studenttb.getColumnModel().getColumn(7).setCellRenderer(new ImageRenderer());
        studenttb.setRowHeight(60);
        
    }
    
    private void fetchallstudent()
    {
        String dept = deptcb.getSelectedItem().toString();
        try {
            HttpResponse<String> response = Unirest.get("http://localhost:8080/adminviewstudent").queryString("dept", dept).asString();

            String ans10 = response.getBody();
            
            System.out.println(ans10);
            StringTokenizer st = new StringTokenizer(ans10, "$$");
            
            al2.clear();
            while (st.hasMoreTokens()) {
                String sdet = st.nextToken();
                StringTokenizer st2 = new StringTokenizer(sdet, ";;;");
                
                String si = st2.nextToken();
                String sn = st2.nextToken();
                String fn = st2.nextToken();
                String mn = st2.nextToken();

                String add = st2.nextToken();
                String em = st2.nextToken();
                                String mob = st2.nextToken();

                String depart = st2.nextToken();
                String sem = st2.nextToken();
                String course = st2.nextToken();
                String photo = st2.nextToken();

                

//               CourseDetails ob= new CourseDetails(cn, dept, des, sem);
//               al.add(ob);
               al2.add(new Student(si,sn,fn,mn,add,em,depart,sem,course,mob,photo));
                
                

            }
            
            tm2.fireTableDataChanged();
            //table model
            
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    class mytablemodel2 extends AbstractTableModel
    {
        @Override
        public int getRowCount() 
        {
           return al2.size();
        }

        @Override
        public int getColumnCount() 
        {
           return 8;
        }

        @Override
        public String getColumnName(int j)
        {
             String c[] = { "Student Name","Father's Name","Mother's Name","Address","Email_id", 
                 "Department", "Semester", "Course", "Mobile No." };
             return c[j];
        }
        
        @Override
        public Object getValueAt(int i, int j)
        {
           
            
            if(j==0) 
                return al2.get(i).sn;
            else if(j==1)
                return al2.get(i).fn;
            else if(j==2)
                return al2.get(i).mn;
            else if(j==3)
                return al2.get(i).add;
            else if(j==4)
                return al2.get(i).em;
            else if(j==5)
                return al2.get(i).dept;
            else if(j==6)
                return al2.get(i).sem;
            else if(j==7)
                return al2.get(i).course;   
            else
                return al2.get(i).mob;
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
     class ImageRenderer extends DefaultTableCellRenderer {

        JLabel lbl = new JLabel();

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            try {
                URL url = new URL("http://localhost:8080/getresource/" + al2.get(row).photo);
                BufferedImage img = ImageIO.read(url);
                Image newimg = img.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                lbl.setIcon(new ImageIcon(newimg));

            } catch (Exception ex) {
                ex.printStackTrace();
            }

            return lbl;

        }

    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studenttb = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        deptcb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        studenttb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(studenttb);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 210, 1110, 380);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-view-48.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(790, 120, 50, 50);

        deptcb.setBackground(new java.awt.Color(255, 255, 255));
        deptcb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deptcb.setForeground(new java.awt.Color(51, 51, 51));
        deptcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.S.E", "Management", "E.E", "M.E" }));
        jPanel1.add(deptcb);
        deptcb.setBounds(470, 130, 310, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-graduate-96.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 0, 90, 100);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Students");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(600, 50, 90, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(600, 20, 90, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Show");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(800, 170, 33, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Select Department");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(320, 130, 140, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 50, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Delete");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(610, 680, 50, 16);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-delete-64.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(600, 620, 70, 60);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Back");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 40, 50, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(930, 670, 310, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1240, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fetchallstudent();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        

        int row = studenttb.getSelectedRow();
        if(row==-1)
        {
            JOptionPane.showMessageDialog(this, "No Row Selected");
        }
        else
        {
            int sel = JOptionPane.showConfirmDialog(this, "Are You Sure You Want to Delete", "Uni LMS Delete Confirm Dialog Box", JOptionPane.YES_NO_OPTION);
            if(sel==JOptionPane.YES_OPTION)
            {

            String si = al2.get(row).si;

            try
            {
                HttpResponse<String> response = Unirest.get("http://localhost:8080/admindeletestudent")
                .queryString("studentid",si).asString();

                if(response.getStatus()==200)
                {
                    String feedback4 = response.getBody();
                    if(feedback4.equals("Student Deleted !!!"))
                    {

                        fetchallstudent();
//                        JOptionPane.showMessageDialog(this, "Student Deleted !!!");
                        JOptionPane.showMessageDialog(this, """
                                                                !!! Done !!!
                                                                Student Record Deleted""", "Uni LMS Manage Student", JOptionPane.PLAIN_MESSAGE, ic);

                    }

                    else{
                        System.out.println(response.getStatusText());
                    }
                }
            }

            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
            else
            {
                JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Operation Cancelled""", "Uni LMS Manage Student", JOptionPane.PLAIN_MESSAGE, ic);
            }
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> deptcb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studenttb;
    // End of variables declaration//GEN-END:variables
}
