/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author tushar
 */
public class StudentViewNotes extends javax.swing.JFrame {

    /**
     * Creates new form StudentViewNotes
     */
    String studentname = GlobalClass.loggedinstudent;
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");

    ArrayList<StudentNotesArray> al;
    mytablemodel4 tm4;


    public StudentViewNotes() {
        initComponents();
                try
        {
            HttpResponse<String> response = Unirest.get("http://localhost:8080/studentsetname").queryString("id", studentname).asString(); 
            if(response.getStatus()==200)
            {
            String anss = response.getBody();
//            System.out.println(anss);

            StringTokenizer st3 = new StringTokenizer(anss, ";;;");
            while (st3.hasMoreTokens()) {
                String tname,dep,course,sem;
                tname = st3.nextToken();
                tname= tname.toUpperCase();
                dep = st3.nextToken();
                
                course = st3.nextToken();
                course = course.toUpperCase();
                sem = st3.nextToken();

//              photo1 = st3.nextToken(); 

             name.setText(tname+"!");
             department.setText(dep);
             courselb.setText(course);
             semlb.setText(sem);

            }
         
            }
        }
        
        catch (Exception ex) 
        {
                ex.printStackTrace();
       }
                
        al = new ArrayList<>();
        tm4 = new mytablemodel4();
        jTable1.setModel(tm4);
        setSize(1235, 850);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        fetchbt = new javax.swing.JButton();
        courselb = new javax.swing.JLabel();
        semlb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 270, 1140, 480);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WELCOME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(510, -10, 130, 50);

        name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("CHANDPREET SINGH!");
        jPanel1.add(name);
        name.setBounds(390, 20, 370, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Department of");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 60, 250, 40);

        department.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        department.setForeground(new java.awt.Color(51, 51, 51));
        department.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        department.setText("jLabel2");
        jPanel1.add(department);
        department.setBounds(450, 100, 250, 40);

        fetchbt.setBackground(new java.awt.Color(255, 255, 255));
        fetchbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-view-48.png"))); // NOI18N
        fetchbt.setBorder(null);
        fetchbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetchbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchbtActionPerformed(evt);
            }
        });
        jPanel1.add(fetchbt);
        fetchbt.setBounds(970, 160, 60, 60);

        courselb.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        courselb.setForeground(new java.awt.Color(51, 51, 51));
        courselb.setText("Course");
        jPanel1.add(courselb);
        courselb.setBounds(370, 190, 90, 20);

        semlb.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        semlb.setForeground(new java.awt.Color(51, 51, 51));
        semlb.setText("Semester");
        jPanel1.add(semlb);
        semlb.setBounds(730, 190, 110, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Download");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1040, 220, 60, 17);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/download-floppy-data.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1);
        jButton1.setBounds(1040, 160, 60, 60);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Show");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(970, 220, 60, 17);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 50, 50);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Back");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-3, 50, 60, 16);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(920, 0, 300, 100);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Course:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 190, 90, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Semester:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(620, 190, 110, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1220, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fetchbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchbtActionPerformed
        // TODO add your handling code here:
        fetchnotes();
    }//GEN-LAST:event_fetchbtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void fetchnotes()
    {
        try
        {
            
        
        String dept = department.getText();
        System.out.println(dept);
        String course = courselb.getText();
        String sem = semlb.getText();
        
        
        HttpResponse<String> response = Unirest.get("http://localhost:8080/studentviewnotes").queryString("depart",dept)
                .queryString("course",course)
                .queryString("sem",sem)
                .asString();
        
        
        String ans = response.getBody();
        StringTokenizer st = new StringTokenizer(ans,"$$");
        
        al.clear();
            
            while(st.hasMoreTokens())
            {
                String vnotes = st.nextToken();
                StringTokenizer st2 = new StringTokenizer(vnotes,";;;");
                
                String title = st2.nextToken();
                String details = st2.nextToken();
                String type = st2.nextToken();
                String file = st2.nextToken();
                String date = st2.nextToken();
                
                al.add(new StudentNotesArray(title,details,type,file,date));
                
            }
            tm4.fireTableDataChanged();
        
        }
        
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        
    }
    
    class mytablemodel4 extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

         public String getColumnName(int j) {
            String c[] = {"Title","Details","type"
            ,"Date and Time", "File"};
            return c[j];
        }

        @Override
        public Object getValueAt(int i, int j) {

            if (j == 0) {
               return al.get(i).title;
            } else if (j == 1) {
               return al.get(i).details;
            } else if (j == 2) {
               return al.get(i).type;
            } 
            else if (j==3)
            {
               return al.get(i).date;
            }
            else
            {
                return al.get(i).file;
            }

        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentViewNotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courselb;
    private javax.swing.JLabel department;
    private javax.swing.JButton fetchbt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel semlb;
    // End of variables declaration//GEN-END:variables
}
