/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author tushar
 */
public class StudentChat extends javax.swing.JFrame {

    /**
     * Creates new form StudentChat
     */
    String studentid = GlobalClass.loggedinstudent;
    String name;
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");

    public StudentChat() {
        initComponents();
        try {
            HttpResponse<String> response = Unirest.get("http://localhost:8080/studentsetname").queryString("id", studentid).asString();

            String anss = response.getBody();
            System.out.println(anss);

            StringTokenizer st3 = new StringTokenizer(anss, ";;;");
            while (st3.hasMoreTokens()) {
                name = st3.nextToken();

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        jChatArea.setContentType("text/html");
        setSize(700, 700);
        loadchat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jChatArea = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        talb = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        submitbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jScrollPane1.setViewportView(jChatArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 40, 930, 320);

        talb.setColumns(20);
        talb.setRows(5);
        jScrollPane2.setViewportView(talb);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(260, 380, 470, 130);

        jLabel1.setText("Question");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 410, 120, 50);

        submitbt.setText("Submit");
        submitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtActionPerformed(evt);
            }
        });
        jPanel1.add(submitbt);
        submitbt.setBounds(800, 410, 170, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtActionPerformed
        // TODO add your handling code here:

        String question = talb.getText();
        if (!question.isEmpty()) {
            try {
                HttpResponse<String> response = Unirest.get("http://localhost:8080/studentaskquestion")
                        .queryString("id", studentid)
                        .queryString("name", name)
                        .queryString("question", question)
                        .asString();

                if (response.getStatus() == 200) {
                    String feedback5 = response.getBody();
                    if (feedback5.equals("Fails!!!")) {
                        //                        JOptionPane.showMessageDialog(this, "Fails!!!");
                        JOptionPane.showMessageDialog(this, """
                                !!! OOPS !!!
                                Error Occured
                                !!! Try Again !!!""", "Uni LMS Studnet Ask Question", JOptionPane.PLAIN_MESSAGE, ic);
                    } else {
                        loadchat();
                        //                       String output = "Your Output is";
                        //                        JOptionPane.showMessageDialog(this, "Your Student Id: " + feedback5 + "\n Your Password is: " + pass2);
                        JOptionPane.showMessageDialog(this, """
                                    !!! Done !!!
                                    Notes Added
                                    \nReference Id Generated:""" + feedback5,
                                "Uni LMS Student Ask Question", JOptionPane.PLAIN_MESSAGE, ic);

                        //                        department.setText(null);
                    }
                } else {
                    System.out.println(response.getStatusText());
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_submitbtActionPerformed

    private void loadchat() {
        try {
            HttpResponse<String> response = Unirest.get("http://localhost:8080/studentfetchchat")
                    .queryString("id", studentid)
                    .asString();

            if (response.getStatus() == 200) {

                String ans4 = response.getBody();
                String chat = "";
                StringTokenizer st4 = new StringTokenizer(ans4, "#$#");
                while (st4.hasMoreTokens()) {
                    String st3 = st4.nextToken();
                    StringTokenizer st = new StringTokenizer(st3, ";;;");
                    String ques = st.nextToken();
                    String answer = st.nextToken();
                    String teachname = st.nextToken();
                    if (answer.equals("na")) {
                        chat += "<h1 align=\"left\" style=\"color:red;\"><b>Question:- </b>" + ques + "</h1>";
                        chat += "<h2 align=\"left\" style=\"color:black;\">Not Answered Yet !!</h2>";
                        chat += "<h1 style=\"color:black;\"><b>____________________________________________________</b></h1>";
                    } else {
                        chat += "<h1 align=\"left\" style=\"color:green;\"><b>Question:- </b>" + ques + "</h1>";
                        chat += "<h2 align=\"left\" style=\"color:blue;\"><i>Answer By:- </i>" + teachname + "</h2>";
                        chat += "<p align=\"left\" style=\"color:black;\">" + answer + "</p>";
                        chat += "<h1 style=\"color:black;\"><b>____________________________________________________</b></h1>";

                    }
                }
                jChatArea.setText(chat);

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jChatArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submitbt;
    private javax.swing.JTextArea talb;
    // End of variables declaration//GEN-END:variables
}
