/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author tushar
 */
public class TeacherViewProfile extends javax.swing.JFrame {

    /**
     * Creates new form TeacherViewProfile
     */
    String teachername = GlobalClass.loggedinteacher;

    public TeacherViewProfile() {
        initComponents();

        try {
            HttpResponse<String> response = Unirest.get(GlobalClass.serverAddress+"teacherviewprofile").queryString("id", teachername).asString();

            String anss = response.getBody();
            System.out.println(anss);

            StringTokenizer st3 = new StringTokenizer(anss, ";;;");
            while (st3.hasMoreTokens()) {
                String ti1, tn1, fn1, add1, em1, phn1, qual1, dept1,photo1;
                ti1 = st3.nextToken().toUpperCase();
                tn1 = st3.nextToken().toUpperCase();
                fn1 = st3.nextToken().toUpperCase();
                
                add1 = st3.nextToken().toUpperCase();
                em1 = st3.nextToken().toUpperCase();
                phn1 = st3.nextToken().toUpperCase();
                qual1 = st3.nextToken().toUpperCase();
                dept1 = st3.nextToken().toUpperCase();
                photo1 = st3.nextToken(); 
                

              
                tilb.setText(ti1);
                tnlb.setText(tn1);
                fnlb.setText(fn1);
                addlb.setText(add1);
                emlb.setText(em1);
                phnlb.setText(phn1);
                quallb.setText(qual1);
                deptlb.setText(dept1);
                
                
                
                try {
                    URL url = new URL(GlobalClass.serverAddress+"getresource/" + photo1);
                    BufferedImage img = ImageIO.read(url);
                    Image newimg = img.getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
                    photolb.setIcon(new ImageIcon(newimg));

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }

//            System.out.println(ti1,tn1,fn1,add1,em1,phn1,qual1,dept1);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        setTitle("Uni LMS Teacher View Profile");
        setResizable(false);
        setSize(1155, 738);
        setLocationRelativeTo(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tilb = new javax.swing.JLabel();
        tnlb = new javax.swing.JLabel();
        fnlb = new javax.swing.JLabel();
        addlb = new javax.swing.JLabel();
        emlb = new javax.swing.JLabel();
        phnlb = new javax.swing.JLabel();
        quallb = new javax.swing.JLabel();
        deptlb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        photolb = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        ChangePasswordPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        changebt = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        tilb.setBackground(new java.awt.Color(255, 255, 255));
        tilb.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tilb.setForeground(new java.awt.Color(51, 51, 51));
        tilb.setText("Teacher Id");
        jPanel1.add(tilb);
        tilb.setBounds(400, 200, 240, 20);

        tnlb.setBackground(new java.awt.Color(255, 255, 255));
        tnlb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tnlb.setForeground(new java.awt.Color(51, 51, 51));
        tnlb.setText("Teacher Name");
        jPanel1.add(tnlb);
        tnlb.setBounds(100, 390, 140, 20);

        fnlb.setBackground(new java.awt.Color(255, 255, 255));
        fnlb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fnlb.setForeground(new java.awt.Color(51, 51, 51));
        fnlb.setText("Father Name");
        jPanel1.add(fnlb);
        fnlb.setBounds(400, 300, 240, 17);

        addlb.setBackground(new java.awt.Color(255, 255, 255));
        addlb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addlb.setForeground(new java.awt.Color(51, 51, 51));
        addlb.setText("Address");
        jPanel1.add(addlb);
        addlb.setBounds(400, 500, 250, 60);

        emlb.setBackground(new java.awt.Color(255, 255, 255));
        emlb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emlb.setForeground(new java.awt.Color(51, 51, 51));
        emlb.setText("Email Id");
        jPanel1.add(emlb);
        emlb.setBounds(400, 400, 240, 20);

        phnlb.setBackground(new java.awt.Color(255, 255, 255));
        phnlb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        phnlb.setForeground(new java.awt.Color(51, 51, 51));
        phnlb.setText("Phone Number");
        jPanel1.add(phnlb);
        phnlb.setBounds(400, 640, 240, 20);

        quallb.setBackground(new java.awt.Color(255, 255, 255));
        quallb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        quallb.setForeground(new java.awt.Color(51, 51, 51));
        quallb.setText("Qualification");
        jPanel1.add(quallb);
        quallb.setBounds(780, 430, 280, 20);

        deptlb.setBackground(new java.awt.Color(255, 255, 255));
        deptlb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deptlb.setForeground(new java.awt.Color(51, 51, 51));
        deptlb.setText("Department");
        jPanel1.add(deptlb);
        deptlb.setBounds(780, 330, 280, 20);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Department");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(780, 290, 110, 50);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Back");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 50, 50, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Your Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 350, 110, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Father Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 250, 180, 40);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 460, 110, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Email Id");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 350, 110, 50);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Phone Number");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 600, 110, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Qualification");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(780, 390, 110, 40);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(850, 0, 290, 110);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-qualification-48.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(720, 390, 50, 50);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-address-48.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(350, 460, 40, 50);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-checked-identification-documents-48 (1).png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(350, 150, 50, 50);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-department-48.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(720, 290, 50, 50);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-mail-48.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(350, 360, 40, 30);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-name-48 (1).png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(340, 250, 60, 50);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-name-48.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 350, 40, 40);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-phone-48.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(350, 610, 40, 40);

        jPanel2.setLayout(null);

        photolb.setText("jLabel23");
        jPanel2.add(photolb);
        photolb.setBounds(10, 10, 170, 160);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 160, 190, 180);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(100, 410, 190, 3);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(400, 220, 240, 3);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(400, 320, 240, 3);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(400, 420, 240, 3);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(400, 560, 240, 3);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(400, 660, 240, 3);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(780, 350, 240, 3);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(780, 450, 240, 3);

        ChangePasswordPanel1.setBackground(new java.awt.Color(0, 0, 0));
        ChangePasswordPanel1.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-sign-in-form-password-50.png"))); // NOI18N
        jPanel5.add(jLabel14);
        jLabel14.setBounds(0, 0, 50, 50);

        ChangePasswordPanel1.add(jPanel5);
        jPanel5.setBounds(10, 0, 50, 50);

        changebt.setBackground(new java.awt.Color(0, 0, 0));
        changebt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changebt.setForeground(new java.awt.Color(255, 255, 255));
        changebt.setText("Change Password");
        changebt.setBorder(null);
        changebt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changebt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtActionPerformed(evt);
            }
        });
        ChangePasswordPanel1.add(changebt);
        changebt.setBounds(60, 0, 130, 50);

        jPanel1.add(ChangePasswordPanel1);
        ChangePasswordPanel1.setBounds(800, 490, 190, 50);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/profile.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(400, 10, 110, 90);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 53, 137));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Details");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(550, 60, 120, 40);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 53, 137));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Your Profile");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(510, 20, 200, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 48, 50);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Teacher Id");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(400, 150, 150, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1155, 738);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtActionPerformed
        // TODO add your handling code here:

        //        String Name = name.getText();
        //        System.out.println(Name);

        TeacherChangePassword obj = new TeacherChangePassword();
        obj.setVisible(true);
    }//GEN-LAST:event_changebtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherViewProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangePasswordPanel1;
    private javax.swing.JLabel addlb;
    private javax.swing.JButton changebt;
    private javax.swing.JLabel deptlb;
    private javax.swing.JLabel emlb;
    private javax.swing.JLabel fnlb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel phnlb;
    private javax.swing.JLabel photolb;
    private javax.swing.JLabel quallb;
    private javax.swing.JLabel tilb;
    private javax.swing.JLabel tnlb;
    // End of variables declaration//GEN-END:variables
}
