/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author tushar
 */
public class TeacherAddAssisgnment extends javax.swing.JFrame {

    /**
     * Creates new form TeacherAddAssisgnment
     */
    String teachername = GlobalClass.loggedinteacher;

    String filetype;
    File file;
    String select;
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");

    public TeacherAddAssisgnment() {
        initComponents();

        try {
            HttpResponse<String> response = Unirest.get(GlobalClass.serverAddress+"teachersetname").queryString("id", teachername).asString();
            if (response.getStatus() == 200) {
                String anss = response.getBody();
//            System.out.println(anss);

                StringTokenizer st3 = new StringTokenizer(anss, ";;;");
                while (st3.hasMoreTokens()) {
                    String tname, dep;
                    tname = st3.nextToken();
                    tname = tname.toUpperCase();
                    dep = st3.nextToken();

//              photo1 = st3.nextToken(); 
                    name.setText(tname + "!");
                    department.setText(dep);

                }

            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }

        fetchcourse();
        setSize(1115, 720);
        setTitle("Uni LMS Teacher Add Assignments");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    private void fetchcourse() {
        System.out.println("Hello im function");
        new Thread(new Runnable() {
            @Override
            public void run() {

                String depart = department.getText();
                try {
                    ccb.removeAllItems();

                    HttpResponse<String> response = Unirest.get(GlobalClass.serverAddress+"getcourse").queryString("depart", depart).asString();

                    //  System.out.println(ans4);
                    if (response.getStatus() == 200) {
                        ccb.removeAllItems();
                        String ans4 = response.getBody();

                        StringTokenizer st4 = new StringTokenizer(ans4, "#$#");
                        while (st4.hasMoreTokens()) {

                            ccb.addItem(st4.nextToken());
                        }

                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        }).start();
    }

    private void fetchsemester() {
        System.out.println("called");
        new Thread(new Runnable() {
            @Override
            public void run() {
                String course = ccb.getSelectedItem().toString();
                System.out.println("course---" + course);
                String de = department.getText();
                try {
                    HttpResponse<String> response = Unirest.get(GlobalClass.serverAddress+"getsemester").queryString("course", course).queryString("de", de).asString();
                    if (response.getStatus() == 200) {
                        semcb.removeAllItems();
                        String ans5 = response.getBody();

                        StringTokenizer st5 = new StringTokenizer(ans5, "#$#$");
                        while (st5.hasMoreTokens()) {

                            semcb.addItem(st5.nextToken());
                        }

                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ccb = new javax.swing.JComboBox<>();
        name = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        semcb = new javax.swing.JComboBox<>();
        titlelb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        browsebt = new javax.swing.JButton();
        lbpath = new javax.swing.JLabel();
        lbphoto = new javax.swing.JLabel();
        addassignmentbt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailslb = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        resetbt = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        submdatetf = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        ccb.setBackground(new java.awt.Color(255, 255, 255));
        ccb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ccb.setForeground(new java.awt.Color(51, 51, 51));
        ccb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        ccb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ccbItemStateChanged(evt);
            }
        });
        jPanel2.add(ccb);
        ccb.setBounds(140, 200, 380, 40);

        name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("CHANDPREET SINGH!");
        jPanel2.add(name);
        name.setBounds(390, 30, 370, 50);

        department.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        department.setForeground(new java.awt.Color(51, 51, 51));
        department.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        department.setText("CSE");
        jPanel2.add(department);
        department.setBounds(460, 120, 240, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Department of ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(470, 80, 220, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WELCOME");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(510, 0, 130, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Select Course");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 180, 130, 20);

        semcb.setBackground(new java.awt.Color(255, 255, 255));
        semcb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        semcb.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(semcb);
        semcb.setBounds(140, 300, 380, 40);

        titlelb.setBackground(new java.awt.Color(255, 255, 255));
        titlelb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titlelb.setForeground(new java.awt.Color(51, 51, 51));
        titlelb.setBorder(null);
        titlelb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titlelbActionPerformed(evt);
            }
        });
        jPanel2.add(titlelb);
        titlelb.setBounds(140, 400, 380, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reset");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(850, 560, 110, 20);

        browsebt.setBackground(new java.awt.Color(255, 255, 255));
        browsebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-browse-64.png"))); // NOI18N
        browsebt.setBorder(null);
        browsebt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        browsebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebtActionPerformed(evt);
            }
        });
        jPanel2.add(browsebt);
        browsebt.setBounds(890, 180, 70, 70);

        lbpath.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbpath.setForeground(new java.awt.Color(51, 51, 51));
        lbpath.setText("File Name Will Appear Here");
        jPanel2.add(lbpath);
        lbpath.setBounds(700, 230, 190, 30);

        lbphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lbphoto);
        lbphoto.setBounds(660, 230, 32, 32);

        addassignmentbt.setBackground(new java.awt.Color(255, 255, 255));
        addassignmentbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/note (1).png"))); // NOI18N
        addassignmentbt.setBorder(null);
        addassignmentbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addassignmentbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addassignmentbtActionPerformed(evt);
            }
        });
        jPanel2.add(addassignmentbt);
        addassignmentbt.setBounds(710, 450, 110, 110);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        detailslb.setBackground(new java.awt.Color(255, 255, 255));
        detailslb.setColumns(20);
        detailslb.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        detailslb.setRows(5);
        jScrollPane1.setViewportView(detailslb);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(140, 490, 380, 81);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Add Some Details of Assignment");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(140, 460, 260, 20);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(140, 430, 380, 10);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Submission Date");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(660, 320, 240, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Select Semester");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(140, 280, 130, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Only PDF Files*");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(890, 250, 90, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(800, 590, 300, 100);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Back");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 50, 50, 20);

        resetbt.setBackground(new java.awt.Color(255, 255, 255));
        resetbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-refresh-64.png"))); // NOI18N
        resetbt.setBorder(null);
        resetbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtActionPerformed(evt);
            }
        });
        jPanel2.add(resetbt);
        resetbt.setBounds(850, 450, 110, 110);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Publish Assignment");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(680, 560, 150, 20);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(0, 0, 50, 50);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Select File");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(660, 180, 190, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Add Title to Your Assignment");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(140, 370, 240, 20);

        submdatetf.setBackground(new java.awt.Color(255, 255, 255));
        submdatetf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        submdatetf.setForeground(new java.awt.Color(51, 51, 51));
        submdatetf.setBorder(null);
        jPanel2.add(submdatetf);
        submdatetf.setBounds(660, 340, 310, 40);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(660, 380, 310, 10);

        jDate.setDateFormatString("dd-MM-yyyy");
        jDate.setMaxSelectableDate(null);
        jPanel2.add(jDate);
        jDate.setBounds(800, 320, 160, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 690);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ccbItemStateChanged
        // TODO add your handling code
        fetchsemester();
    }//GEN-LAST:event_ccbItemStateChanged

    private void titlelbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titlelbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titlelbActionPerformed

    private void browsebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebtActionPerformed
        // TODO add your handling code here:

        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filterpdf = new FileNameExtensionFilter("Pdf Files", "pdf");
//        FileNameExtensionFilter filteraudio = new FileNameExtensionFilter("Audio Files", "mp3");
//        FileNameExtensionFilter filtervideo = new FileNameExtensionFilter("Video Files", "mp4");
        jfc.setAcceptAllFileFilterUsed(false);
        ImageIcon icon = null;

        jfc.setFileFilter(filterpdf);
        icon = new ImageIcon("src/pdf-file.png");
        filetype = "Pdf";

        int showOpenDialog = jfc.showOpenDialog(this);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            lbpath.setText(file.getName());
            lbphoto.setIcon(icon);
        }

    }//GEN-LAST:event_browsebtActionPerformed

    private void addassignmentbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addassignmentbtActionPerformed

        // TODO add your handling code here:
        String d1 = jDate.getDate().toString();

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

        Date d2 = jDate.getDate();
        String subDate = sdf.format(d2);

        Date d = new Date();
        //            SimpleDateFormat(");
        String date = sdf.format(d);

        //            String select = buttonGroup1.getSelection().toString();
        //            System.out.println(select);
        select = "pdf";

        String dept, course, sem, title, details, subdate;
        dept = department.getText();
        course = ccb.getSelectedItem().toString();
        sem = semcb.getSelectedItem().toString();
        title = titlelb.getText();
        details = detailslb.getText();
        subdate = submdatetf.getText();

        if (!title.isEmpty() && !details.isEmpty() && !subdate.isEmpty() && file != null) {

            try {

                HttpResponse<String> response = Unirest.post(GlobalClass.serverAddress+"TeacherAddAssignment")
                        .queryString("dept", dept)
                        .queryString("course", course)
                        .queryString("sem", sem)
                        .queryString("title", title)
                        .queryString("details", details)
                        .queryString("id", teachername)
                        .queryString("date", date)
                        .queryString("type", select)
                        .queryString("subdate", subdate)
                        .field("file", file).asString();

                if (response.getStatus() == 200) {

                    String feedback5 = response.getBody();
                    if (feedback5.equals("Fails!!!")) {
                        //                        JOptionPane.showMessageDialog(this, "Fails!!!");
                        JOptionPane.showMessageDialog(this, """
                                !!! OOPS !!!
                                Error Occured
                                !!! Try Again !!!""", "Uni LMS Teacher Add Assignment", JOptionPane.PLAIN_MESSAGE, ic);
                    } else {
                        //                       String output = "Your Output is";
                        //                        JOptionPane.showMessageDialog(this, "Your Student Id: " + feedback5 + "\n Your Password is: " + pass2);
                        JOptionPane.showMessageDialog(this, """
                                    !!! Done !!!
                                    Notes Added
                                    \nYour Assignment Id Generated:""" + feedback5,
                                "Uni LMS Teacher Add ASsignment", JOptionPane.PLAIN_MESSAGE, ic);

                        //                        department.setText(null);
                        titlelb.setText(null);
                        detailslb.setText(null);
                        file = null;
                        lbphoto.setText(null);

                    }
                } else {
                    System.out.println(response.getStatusText());
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, """
                        !!! OOPS !!!
                        Empty Field Exists
                        !!! All Fields are Required !!!""", "Uni LMS Teacher Add Notes", JOptionPane.PLAIN_MESSAGE, ic);
        }

    }//GEN-LAST:event_addassignmentbtActionPerformed

    private void resetbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtActionPerformed
        // TODO add your handling code here:
        //         department.setText(null);
        titlelb.setText(null);
        detailslb.setText(null);
        lbpath.setText("File Name Will Appear Here");
        file = null;
        lbphoto.setText(null);

    }//GEN-LAST:event_resetbtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherAddAssisgnment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherAddAssisgnment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherAddAssisgnment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherAddAssisgnment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherAddAssisgnment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addassignmentbt;
    private javax.swing.JButton browsebt;
    private javax.swing.JComboBox<String> ccb;
    private javax.swing.JLabel department;
    private javax.swing.JTextArea detailslb;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbpath;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JLabel name;
    private javax.swing.JButton resetbt;
    private javax.swing.JComboBox<String> semcb;
    private javax.swing.JTextField submdatetf;
    private javax.swing.JTextField titlelb;
    // End of variables declaration//GEN-END:variables
}
