/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unilms;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author tushar
 */
public class TeacherAddNotes extends javax.swing.JFrame {

    /**
     * Creates new form TeacherAddNotes
     */
    String teachername = GlobalClass.loggedinteacher;
    String filetype;
    File file;
    String select;
    ImageIcon ic = new ImageIcon("src/Uni Lms.png");
    
    public TeacherAddNotes() {
        initComponents();
        try
        {
            HttpResponse<String> response = Unirest.get(GlobalClass.serverAddress+"teachersetname").queryString("id", teachername).asString(); 
            if(response.getStatus()==200)
            {
            String anss = response.getBody();
//            System.out.println(anss);

            StringTokenizer st3 = new StringTokenizer(anss, ";;;");
            while (st3.hasMoreTokens()) {
                String tname,dep;
                tname = st3.nextToken();
                tname= tname.toUpperCase();
                dep = st3.nextToken();
                
                
                
                

//              photo1 = st3.nextToken(); 

             name.setText(tname+"!");
             department.setText(dep);

            }
         
            }
        }
        
        catch (Exception ex) 
        {
                ex.printStackTrace();
        
        
        
       }  

//        department.setText("C.S.E");
        
        fetchcourse();
       // fetchsemester();
        setSize(1115, 720);
        setResizable(false);
        setTitle("Uni LMS Teacher Add Notes");
//        browsebt.setEnabled(false);
        setLocationRelativeTo(null);
        
        
//        if(jrbpdf.isSelected() || jrbaudio.isSelected() || jrbvideo.isSelected() )
//        {
//            browsebt.setEnabled(true);
//        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ccb = new javax.swing.JComboBox<>();
        name = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        semcb = new javax.swing.JComboBox<>();
        titlelb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jrbpdf = new javax.swing.JRadioButton();
        jrbaudio = new javax.swing.JRadioButton();
        jrbvideo = new javax.swing.JRadioButton();
        browsebt = new javax.swing.JButton();
        lbpath = new javax.swing.JLabel();
        lbphoto = new javax.swing.JLabel();
        addnotebt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailslb = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        resetbt = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        ccb.setBackground(new java.awt.Color(255, 255, 255));
        ccb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ccb.setForeground(new java.awt.Color(51, 51, 51));
        ccb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        ccb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ccbItemStateChanged(evt);
            }
        });
        jPanel1.add(ccb);
        ccb.setBounds(140, 200, 380, 40);

        name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("CHANDPREET SINGH!");
        jPanel1.add(name);
        name.setBounds(390, 30, 370, 50);

        department.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        department.setForeground(new java.awt.Color(51, 51, 51));
        department.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        department.setText("jLabel2");
        jPanel1.add(department);
        department.setBounds(460, 120, 240, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Department of ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 80, 220, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WELCOME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(510, 0, 130, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Select Course");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 180, 130, 20);

        semcb.setBackground(new java.awt.Color(255, 255, 255));
        semcb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        semcb.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(semcb);
        semcb.setBounds(140, 300, 380, 40);

        titlelb.setBackground(new java.awt.Color(255, 255, 255));
        titlelb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titlelb.setForeground(new java.awt.Color(51, 51, 51));
        titlelb.setBorder(null);
        titlelb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titlelbActionPerformed(evt);
            }
        });
        jPanel1.add(titlelb);
        titlelb.setBounds(140, 400, 380, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reset");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(850, 520, 110, 20);

        buttonGroup1.add(jrbpdf);
        jrbpdf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jrbpdf.setForeground(new java.awt.Color(51, 51, 51));
        jrbpdf.setText("PDF");
        jPanel1.add(jrbpdf);
        jrbpdf.setBounds(670, 210, 98, 20);

        buttonGroup1.add(jrbaudio);
        jrbaudio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jrbaudio.setForeground(new java.awt.Color(51, 51, 51));
        jrbaudio.setText("Audio");
        jrbaudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbaudioActionPerformed(evt);
            }
        });
        jPanel1.add(jrbaudio);
        jrbaudio.setBounds(780, 210, 98, 20);

        buttonGroup1.add(jrbvideo);
        jrbvideo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jrbvideo.setForeground(new java.awt.Color(51, 51, 51));
        jrbvideo.setText("Video");
        jPanel1.add(jrbvideo);
        jrbvideo.setBounds(890, 210, 98, 20);

        browsebt.setBackground(new java.awt.Color(255, 255, 255));
        browsebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-browse-64.png"))); // NOI18N
        browsebt.setBorder(null);
        browsebt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        browsebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebtActionPerformed(evt);
            }
        });
        jPanel1.add(browsebt);
        browsebt.setBounds(900, 280, 70, 70);

        lbpath.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbpath.setForeground(new java.awt.Color(51, 51, 51));
        lbpath.setText("File Name Will Appear Here");
        jPanel1.add(lbpath);
        lbpath.setBounds(710, 320, 190, 30);

        lbphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbphoto);
        lbphoto.setBounds(670, 320, 32, 32);

        addnotebt.setBackground(new java.awt.Color(255, 255, 255));
        addnotebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/note (1).png"))); // NOI18N
        addnotebt.setBorder(null);
        addnotebt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addnotebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnotebtActionPerformed(evt);
            }
        });
        jPanel1.add(addnotebt);
        addnotebt.setBounds(710, 410, 110, 110);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        detailslb.setBackground(new java.awt.Color(255, 255, 255));
        detailslb.setColumns(20);
        detailslb.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        detailslb.setRows(5);
        jScrollPane1.setViewportView(detailslb);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 490, 380, 81);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Add Some Detail of Your Notes");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(140, 460, 260, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(140, 430, 380, 10);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Add Title to Your Notes");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 370, 180, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Select Semester");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 280, 130, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Select Type of Your File");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(670, 180, 190, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/Uni Lms.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(800, 580, 300, 110);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Back");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 50, 50, 20);

        resetbt.setBackground(new java.awt.Color(255, 255, 255));
        resetbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/icons8-refresh-64.png"))); // NOI18N
        resetbt.setBorder(null);
        resetbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtActionPerformed(evt);
            }
        });
        jPanel1.add(resetbt);
        resetbt.setBounds(850, 410, 110, 110);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Publish Notes");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(710, 520, 110, 20);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unilms/back.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(0, 0, 50, 50);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Select File");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(670, 280, 190, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void fetchcourse()
    {
        System.out.println("Hello im function");
         new Thread(new Runnable() {
            @Override
            public void run() {

                String depart = department.getText();
                try {
                    ccb.removeAllItems();

                    HttpResponse<String> response = Unirest.get(GlobalClass.serverAddress+"getcourse").queryString("depart", depart).asString();

                    //  System.out.println(ans4);
                    if (response.getStatus() == 200) {
                        ccb.removeAllItems();
                        String ans4 = response.getBody();

                        StringTokenizer st4 = new StringTokenizer(ans4, "#$#");
                        while (st4.hasMoreTokens()) {

                            ccb.addItem(st4.nextToken());
                        }

                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        }).start();
    }
    
    private void fetchsemester()
    {
        System.out.println("called");
      new Thread(new Runnable() {
            @Override
            public void run() {
                String course = ccb.getSelectedItem().toString();
                System.out.println("course---"+course);
                String de = department.getText();
                try {
                    HttpResponse<String> response = Unirest.get(GlobalClass.serverAddress+"getsemester").queryString("course", course).queryString("de", de).asString();
                    if (response.getStatus() == 200) {
                        semcb.removeAllItems();
                        String ans5 = response.getBody();

                        StringTokenizer st5 = new StringTokenizer(ans5, "#$#$");
                        while (st5.hasMoreTokens()) {

                            semcb.addItem(st5.nextToken());
                        }

                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }
        }).start();  
    }
    
    
    
    private void ccbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ccbItemStateChanged
        // TODO add your handling code 
        fetchsemester();
    }//GEN-LAST:event_ccbItemStateChanged

    private void jrbaudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbaudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbaudioActionPerformed

    private void browsebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebtActionPerformed
        // TODO add your handling code here:
        
       
        
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filterpdf = new FileNameExtensionFilter("Pdf Files", "pdf");
        FileNameExtensionFilter filteraudio = new FileNameExtensionFilter("Audio Files", "mp3");
        FileNameExtensionFilter filtervideo = new FileNameExtensionFilter("Video Files", "mp4");
        jfc.setAcceptAllFileFilterUsed(false);
        ImageIcon icon = null;
        if (jrbpdf.isSelected()) {
            jfc.setFileFilter(filterpdf);
            icon = new ImageIcon("src/pdf-file.png");
            filetype = "Pdf";
        } else if (jrbaudio.isSelected()) {
            jfc.setFileFilter(filteraudio);
            icon = new ImageIcon("src/audio.png");
            filetype = "Audio";
        } else {
            jfc.setFileFilter(filtervideo);
            icon = new ImageIcon("src/video.png");
            filetype = "Video";
        }

        int showOpenDialog = jfc.showOpenDialog(this);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            lbpath.setText(file.getName());
            lbphoto.setIcon(icon);
        }
        
        
    }//GEN-LAST:event_browsebtActionPerformed

    private void titlelbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titlelbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titlelbActionPerformed

    private void addnotebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnotebtActionPerformed

        // TODO add your handling code here:
        
        
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
//            SimpleDateFormat(");
            String date = sdf.format(d);
            
            
            
            
//            String select = buttonGroup1.getSelection().toString();
//            System.out.println(select);
            
            
            if(jrbpdf.isSelected())
            {
                select = "pdf";
            }
            else if (jrbaudio.isSelected())
            {
                select ="audio(mp3)";
            }
            else
            {
                select ="video(mp4)";
            }
            
            
            String dept,course,sem,title,details;
            dept = department.getText();
            course = ccb.getSelectedItem().toString();
            sem = semcb.getSelectedItem().toString();
            title = titlelb.getText();
            details = detailslb.getText();
            
            if(!title.isEmpty() && !details.isEmpty() && file!=null)
            {
                
                try
                {
                    
                
            HttpResponse<String> response = Unirest.post(GlobalClass.serverAddress+"teacheraddnotes")
                    .queryString("dept",dept)
                    .queryString("course", course)
                    .queryString("sem",sem)
                    .queryString("title", title)
                    .queryString("details", details)
                    .queryString("id",teachername)
                    .queryString("date",date)
                    .queryString("type",select)
                    .field("file",file).asString();
            
            if (response.getStatus() == 200) {

                    String feedback5 = response.getBody();
                    if (feedback5.equals("Fails!!!")) {
//                        JOptionPane.showMessageDialog(this, "Fails!!!");
                        JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Error Occured
                                                                !!! Try Again !!!""", "Uni LMS Teacher Add Notes", JOptionPane.PLAIN_MESSAGE, ic);
                    } else {
//                       String output = "Your Output is";
//                        JOptionPane.showMessageDialog(this, "Your Student Id: " + feedback5 + "\n Your Password is: " + pass2);
                        JOptionPane.showMessageDialog(this, """
                                                                !!! Done !!!
                                                                Notes Added 
                                                                \nYour Notes Id Generated:""" + feedback5
                                                               
                                                                 , "Uni LMS Teacher Add Notes", JOptionPane.PLAIN_MESSAGE, ic);
                        
//                        department.setText(null);
                        titlelb.setText(null);
                        detailslb.setText(null);
                        file=null;
                        lbphoto.setText(null);

                    }
                } 
                else 
                {
                    System.out.println(response.getStatusText());
                }

                }
            
        
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
            }
            else
            {
                JOptionPane.showMessageDialog(this, """
                                                                !!! OOPS !!!
                                                                Empty Field Exists
                                                                !!! All Fields are Required !!!""", "Uni LMS Teacher Add Notes", JOptionPane.PLAIN_MESSAGE, ic);
            }
               
    }//GEN-LAST:event_addnotebtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void resetbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtActionPerformed
        // TODO add your handling code here:
//         department.setText(null);
         titlelb.setText(null);
         detailslb.setText(null);
         lbpath.setText("File Name Will Appear Here");
         file=null;
         lbphoto.setText(null);
        
    }//GEN-LAST:event_resetbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherAddNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherAddNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherAddNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherAddNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherAddNotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnotebt;
    private javax.swing.JButton browsebt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> ccb;
    private javax.swing.JLabel department;
    private javax.swing.JTextArea detailslb;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jrbaudio;
    private javax.swing.JRadioButton jrbpdf;
    private javax.swing.JRadioButton jrbvideo;
    private javax.swing.JLabel lbpath;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JLabel name;
    private javax.swing.JButton resetbt;
    private javax.swing.JComboBox<String> semcb;
    private javax.swing.JTextField titlelb;
    // End of variables declaration//GEN-END:variables

    
}
